sudo: false
language: go
 
env:
  - GO15VENDOREXPERIMENT=1
 
go:
  - 1.5beta2

install:
  - go get -t -v $(go list ./... | grep -v /vendor/)
 
script:
  - go build
  - ./travis-go
  - cd tool && go build
  - ./tool
